### ISSUE TITLE
NameError: name 'SaveSpectrogram' is not defined

### ISSUE THREAD

**Issue by kwangje** [Jeongseungwoo/Singing-Voice-Separation#1]
```python
Traceback (most recent call last):
  File "CCMixter_process.py", line 35, in <module>
    CCMixter()
  File "CCMixter_process.py", line 29, in CCMixter
    SaveSpectrogram(mix, inst, vocal, audio)
NameError: name 'SaveSpectrogram' is not defined
```
I want to know where is the class "SaveSpectrogram"
Thanks!

**Comment by HonestKwong** [comment]
The fuc "SaveSpectrogram" is in "util.py",  use util.SaveSpectrogram instead.
